### ISSUE TITLE
Allow expanding of json values

### ISSUE THREAD

**Issue by deepakcv** [KohlsTechnology/git2consul-go#48] opened 2020-05-31 17:55 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Expand the keys and nested keys to consul kv store.

**What version of git2consul-go are you using?**
v0.1.1

<pre>
$ git2consul -version
git2consul, version v0.1.2-dev (branch: master, revision: f7da486e18c7223f93a542f966b14673dff7f6f6)
build date: 20200531-16:41:29
go version: go1.12.5
</pre>

**Additional context**
gonsul supports this, but I find the git2consul more friends with multiple repos handling. This feature will definitely be an added plus for git2consul

**Comment by Smiley73** [comment] 2020-06-01 15:45
@deepakcv thanks for the suggestion. Any chance you can work on this and send in a pull request?

**Comment by Smiley73** [comment] 2020-06-01 15:46
Is this potentially a duplicate of #45 ?

**Comment by hongkongkiwi** [comment] 2020-08-10 04:38
I would like this too :) unfortunately I'm not a Go developer, but it's definitely more important than YAML in our use case.

**Closed** 2022-04-22 18:23 UTC
Labels: enhancement
